// Création d'un tableau contenant le profil utilisateur
export const user = {
  firstname: "Damien",
  lastname: "Jean",
  abonnes: 196,
  abonnements: 26,
  date: "1 jan. 1977, 08:00",
};

// Création d'un tableau contenant les posts
export const posts = [
  {
    id: 7,
    profilePic: "assets/img/profile/fred.jpg",
    firstname: "Fred",
    lastname: "",
    date: "25 sept. 2023, 12:22",
    text: 'Venez me voir sur scène le 23 octobre dans la pièce "Javascript et moi"',
    picture: "assets/img/post/theatre.jpeg",
    commentsNumber: 1,
    likesNumber: 28,
  },
  {
    id: 6,
    profilePic: "assets/img/profile/raphael.jpg",
    firstname: "Raph",
    lastname: "",
    date: "25 sept. 2023, 15:02",
    text: "Vous connaissez Sass les gens ?",
    picture: "assets/img/post/sass.jpeg",
    commentsNumber: 1,
    likesNumber: 14,
  },
  {
    id: 5,
    profilePic: "assets/img/profile/nassime.jpg",
    firstname: "Nassime",
    lastname: "",
    date: "28 sept. 2023, 13:35",
    text: "Je sais pas si je vous l'ai déjà dit, mais vous êtes des bonnes personnes",
    picture: "assets/img/post/coeur-mains.jpeg",
    commentsNumber: 1,
    likesNumber: 68,
  },
  {
    id: 4,
    profilePic: "assets/img/profile/mathieu.jpg",
    firstname: "Mathieu",
    lastname: "",
    date: "30 sept. 2023, 11:09",
    text: "En train de coder une IA qui permet d'imiter Julien Lepers, je vous montre ça bientôt #jedisoui",
    picture: "assets/img/post/julien-lepers.jpeg",
    commentsNumber: 1,
    likesNumber: 45,
  },
  {
    id: 3,
    profilePic: "assets/img/profile/adam.jpg",
    firstname: "Adam",
    lastname: "",
    date: "1 oct. 2023, 10:02",
    text: "Moi quand je perds 4h de taf car j'ai oublié de commit",
    picture: "assets/img/post/sad-meme.jpeg",
    commentsNumber: 1,
    likesNumber: 34,
  },
  {
    id: 2,
    profilePic: "assets/img/profile/victor-ga.jpg",
    firstname: "Victor Ga",
    lastname: "",
    date: "1 oct. 2023, 15:02",
    text: "Le meilleur film de tous les temps !",
    picture: "assets/img/post/die-hard.jpeg",
    commentsNumber: 1,
    likesNumber: 121,
  },
  {
    id: 1,
    profilePic: "assets/img/profile/victor-gu.jpg",
    firstname: "Le coach",
    lastname: "",
    date: "2 oct. 2023, 17:35",
    text: "Je viens de passer 3h à me prendre la tête avec les versions MacOS... J'étais censé aller surfer",
    picture: "assets/img/post/angry-mac.jpeg",
    commentsNumber: 2,
    likesNumber: 12,
  },
  {
    id: 0,
    profilePic: "assets/img/profile/sylvain.jpg",
    firstname: "Sylvain",
    lastname: "",
    date: "4 oct. 2023, 09:02",
    text: "Récolte du houblon aujourd'hui ! Dans quelques semaines on pourra déguster la nouvelle cuvée !",
    picture: "assets/img/post/houblon.jpeg",
    commentsNumber: 2,
    likesNumber: 56,
  },
];

// Création d'un tableau contenant les commentaires
export const comments = [
  {
    postId: 7,
    profilePic: "assets/img/profile/dimitri.jpeg",
    firstname: "Dimitri",
    lastname: "",
    date: "11 sept. 2023, 15:59",
    text: "Sylvain t'as toujours été mon chouchou",
  },
  {
    postId: 7,
    profilePic: "assets/img/profile/cedric.jpg",
    firstname: "Cédric",
    lastname: "",
    date: "11 sept. 2023, 17:29",
    text: "J'ai soif !",
  },
  {
    postId: 6,
    profilePic: "assets/img/profile/raphael.jpg",
    firstname: "Raph",
    lastname: "",
    date: "15 sept. 2023, 15:02",
    text: "Les macs ça sert juste à caler des tables",
  },
  {
    postId: 6,
    profilePic: "assets/img/profile/dimitri.jpeg",
    firstname: "Dimitri",
    lastname: "",
    date: "16 sept. 2023, 15:40",
    text: "Raph t'es plus mon chouchou #appleforever",
  },
  {
    postId: 5,
    profilePic: "assets/img/profile/victor-gu.jpg",
    firstname: "Le coach",
    lastname: "",
    date: "3 oct. 2023, 12:02",
    text: "Ah ça vient de là le marcel !",
  },
  {
    postId: 4,
    profilePic: "assets/img/profile/elea.jpeg",
    firstname: "Elea",
    lastname: "",
    date: "2 oct. 2023, 14:02",
    text: "Je connais ça...",
  },
  {
    postId: 3,
    profilePic: "assets/img/profile/antoine.jpg",
    firstname: "Antoine",
    lastname: "",
    date: "4 oct. 2023, 15:02",
    text: "Ce mec est exceptionnel au quotidien ! 👮‍♂️",
  },
  {
    postId: 2,
    profilePic: "assets/img/profile/dimitri.jpeg",
    firstname: "Dimitri",
    lastname: "",
    date: "4 oct. 2023, 15:02",
    text: "Nassime t'es mon chouchou",
  },
  {
    postId: 1,
    profilePic: "assets/img/profile/david.jpg",
    firstname: "David",
    lastname: "",
    date: "4 oct. 2023, 15:02",
    text: "Ouiiii 😍",
  },
  {
    postId: 0,
    profilePic: "assets/img/profile/raphael.jpg",
    firstname: "Raph",
    lastname: "",
    date: "4 oct. 2023, 15:02",
    text: "Je serai au 1er rang !",
  },
];

//creation d'un tableau contenant les messages
export const messageSenders = [
  {
    profilePic: "assets/img/profile/cedric.jpg",
    date: "4 oct 12:29",
    firstname: "Cédric",
    lastname: "",
    message: "Apéro ce soir ?",
  },
  {
    profilePic: "assets/img/profile/dimitri.jpeg",
    date: "4 oct 15:02",
    firstname: "Dimitri",
    lastname: "",
    message: "C'est toi mon chouchou",
  },
  {
    profilePic: "assets/img/profile/antoine.jpg",
    date: "1 oct 23:02",
    firstname: "Antoine",
    lastname: "",
    message: "T'es es où sur le projet ??",
  },
  {
    profilePic: "assets/img/profile/cedric.jpg",
    date: "29 sept 12:12",
    firstname: "Cédric",
    lastname: "",
    message: "Apéro ?",
  },
  {
    profilePic: "assets/img/profile/adam.jpg",
    date: "23 sept 10:57",
    firstname: "Adam",
    lastname: "",
    message: "Petite game ce soir ?",
  },
];
